services:
  cache:
    image: redis:7.0
    container_name: CNT-Cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local